#!/bin/bash

# Run command on each listed git repository, or on all repositories beneath the current directori

. "/data/bin/imports/exit-on-error" || exit 1

usage() {
    exit_with_error "Usage: '$0 [--all | <repository> ... --] <command> ...'" 2
}

[ $# -ge 2 ] || usage

declare -a repositories
all=
if [ "$1" = "--all" ]; then
    all="y"
    shift
    if [ "$1" = "--" ]; then
        shift
    fi
else
    i=0
    while [ $# -gt 0 ] && [ "$1" != "--" ]; do
        repositories[(( i++ ))]="$1"
        shift
    done
    if [ "$1" = "--" ]; then
        shift
    else
        usage
    fi
fi
[ $# -ge 1 ] || usage

rootdir="$PWD"
if [ -n "$all" ]; then
    find . -name ".git" -type d -print0 | sort --zero-terminated | while read -r -d $'\0' gitdir ; do
        full_repos_dir="$(readlink -enq "$rootdir/$gitdir/..")"
        repos_dir="${full_repos_dir#$rootdir/}"
        cd "$full_repos_dir"
        echo "$repos_dir:"
        $@
        echo
        :
    done
else
    for (( i=0 ; i < ${#repositories[@]} ; i++ )); do
        cd "$rootdir" # since it may be a relative path
        full_repos_dir="$(readlink -mnq "${repositories[$i]}")"
        repos_dir="${full_repos_dir#$rootdir/}"
        [ -d "$full_repos_dir" ] || exit_with_error "No such directory: '$full_repos_dir'" 3
        cd "$full_repos_dir"
        echo "$repos_dir:"
        [ -d ".git" ] || exit_with_error "Not a git repository: '$full_repos_dir/.git' not found" 4
        $@
        echo
        :
    done
fi
