#!/bin/bash

EXIT_ON_ERROR_EXITING=
show_err () {
    err=$?

    if [ -n "$EXIT_ON_ERROR_EXITING" ]; then
        return
    fi
    EXIT_ON_ERROR_EXITING="y"
    echo 1>&2 "$0: in command '$BASH_COMMAND'
Error $err occurred, aborting."
}

print_error () {
    local message="$1"

    echo 1>&2 "$0: $message"
}

exit_with_error () {
    if [ -n "$EXIT_ON_ERROR_EXITING" ]; then
        return
    fi
    EXIT_ON_ERROR_EXITING="y"

    local message="$1"
    local exit_code=$2

    print_error "$message"
    if [ -z "$exit_code" ]; then
        exit_code=1
    fi
    exit $exit_code
}

# The importing script is expected to define a function called 'usage_print'
usage_error_exit() {
    local message="$1"

    if [ -n "$message" ]; then
        print_error "ERROR: $message"
    else
        print_error "ERROR: invalid commandline"
    fi
    usage_print
    exit 2
}
